version: '3'

tasks:
  setup-tfvars:
    desc: Create terraform.tfvars with IAM user and SSO role
    cmds:
      - |
        echo "Generating terraform.tfvars..."
        
        # Get IAM user name from AWS_PROFILE or AWS caller identity
        if [ -n "$AWS_PROFILE" ]; then
          IAM_USER="$AWS_PROFILE"
        else
          # Fallback to extracting from caller identity
          IAM_USER=$(aws sts get-caller-identity --query 'Arn' --output text | sed 's/.*user\///')
        fi
        
        # Fetch the admin SSO role name
        SSO_ROLE=$(aws iam list-roles --query 'Roles[?contains(RoleName, `AWSReservedSSO_AdministratorAccess`)].RoleName' --output text | head -n1)
        
        # Write to terraform.tfvars
        cat > terraform.tfvars <<EOF
        iam_user_name         = "$IAM_USER"
        admin_sso_role_name   = "$SSO_ROLE"
        EOF
        
        echo "terraform.tfvars created with:"
        echo "  iam_user_name: $IAM_USER"
        echo "  admin_sso_role_name: $SSO_ROLE"
